### PR TITLE
Release 0.3.4: modtool fix

### PR DESCRIPTION
**Pull request by AsriFox**
In previous releases, I forgot to check if python scripts are included. The `src/**` line in `.vscodeignore` is the reason they weren't. Now they are included.

### CODE REVIEW

**Comment by IvanNovak1004** [comment]
I want to add you as an extension owner in VS code marketplace. Please provide me you user account id.
Screenshot from 2024-01-25 09-57-44

**Comment by AsriFox** [comment]
Isn't it just my GitHub username - AsriFox?

https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/add-organization-users#add-users-to-your-organization

Otherwise, I don't know where to find it.

**Comment by IvanNovak1004** [comment]
Do you have Azure account? I cannot find you there

**Comment by IvanNovak1004** [comment]
you have to create it

**Comment by AsriFox** [comment]
I have an Azure account. It says that my Microsoft account username is "asrifox@yandex.ru", though. 
Screenshot_20240125_123552

**Comment by IvanNovak1004** [comment]
Screenshot from 2024-01-31 08-50-25
Sorry Oleg for late response. But i still have issues adding you to the marketplace, i think i need User Id...

see this also:
Screenshot from 2024-01-31 08-53-38

**Comment by AsriFox** [comment]
82f8bc8e-97c0-6909-bf00-a588a58c3c82

**Comment by IvanNovak1004** [comment]
You are added as owner too. It is in your hands now, take a good care of our extension :)

**Comment by AsriFox** [comment]
Great, thank you!   
Should I keep opening PRs when new versions come?

**Pull request merged**
